#! bin/bash
Tenable Nessus--> Automated scanning for Assesment Vulnerabilities--BEST
Qualys VMDR--->  Automated scanning for Assesment Vulnerabilities
Rapid7 Insight VM--->Own by metaploit its exploitation.
OpenVas--Open source user interface is hard to use
